### ISSUE TITLE
在魅族的Flyme 6上，选了联系人后开机自启广播应用收不到，无法产生拨号的Notification，只能手动启动进入应用后才能产生Notification。

### ISSUE THREAD

**Issue by Shawlaw** [Shawlaw/CallInTwo#2]
使用 魅蓝Note2 Flyme 6.2.0.0A(Android 5.1) 和 魅族MX6 Flyme 6.3.0.1A(Android 7.1.1) 进行测试，都是这个样子。
从Log输出上来看，BOOT_COMPLETED的广播的确有发出，系统自带的部分应用也有接收到处理了。
但两步拨号这个应用的Receiver就是收不到这个广播。

而使用Android 8.0原生系统来测试时，重启后却都能正常出来Notification。

**Comment by Shawlaw** [comment]
原因是在于没有持有WAKE_LOCK权限，所以在收到广播后开后台服务时崩溃了，所以没有产生Notification。
在相关提交中补充了WAKE_LOCK权限的申请。

**Comment by Shawlaw** [comment]
崩溃栈如下：

> 02-25 12:43:54.223 2877-2877/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: github.shawlaw.app.callintwo, PID: 2877
                                                 java.lang.RuntimeException: Unable to start service github.shawlaw.app.callintwo.services.LoadNotificationService@827349a with Intent { act=notifyAllContacts cmp=github.shawlaw.app.callintwo/.services.LoadNotificationService }: java.lang.SecurityException: Neither user 10084 nor current process has android.permission.WAKE_LOCK.
                                                     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3343)
                                                     at android.app.ActivityThread.-wrap21(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                  Caused by: java.lang.SecurityException: Neither user 10084 nor current process has android.permission.WAKE_LOCK.
                                                     at android.os.Parcel.readException(Parcel.java:1684)
                                                     at android.os.Parcel.readException(Parcel.java:1637)
                                                     at android.os.IPowerManager$Stub$Proxy.acquireWakeLock(IPowerManager.java:381)
                                                     at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:1232)
                                                     at android.os.PowerManager$WakeLock.acquire(PowerManager.java:1216)
                                                     at android.support.v4.app.JobIntentService$CompatWorkEnqueuer.serviceProcessingStarted(JobIntentService.java:215)
                                                     at android.support.v4.app.JobIntentService.ensureProcessorRunningLocked(JobIntentService.java:609)
                                                     at android.support.v4.app.JobIntentService.onStartCommand(JobIntentService.java:449)
                                                     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3326)
                                                     at android.app.ActivityThread.-wrap21(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by Shawlaw** [comment]
根本原因及分析如下：

1. 基于[Android 8.0对后台服务运行的进一步限制](https://developer.android.com/about/versions/oreo/background.html#services)，所以在收到BOOT_COMPLETED广播后用IntentService来恢复拨号用的Notification这个操作是不适用于8.0及之后的系统的，需要使用Support包内的JobIntentService来进行替换使用。

2. [根据JobIntentService的文档说明](https://developer.android.com/reference/android/support/v4/app/JobIntentService.html) 

> You do not need to use WakefulBroadcastReceiver when using this class. When running on Android O, the JobScheduler will take care of wake locks for you (holding a wake lock from the time you enqueue work until the job has been dispatched and while it is running). When running on previous versions of the platform, this wake lock handling is emulated in the class here by directly calling the PowerManager; this means the application must request the WAKE_LOCK permission.

> 即，在8.0系统开始，JobIntentService能自行处理好WAKE_LOCK相关的问题；但在8.0之前的系统版本上，使用JobIntentService的应用必须要持有WAKE_LOCK的权限，才能正常运行。

3. 而在这个提交之前，两步拨号只替换了IntentService成JobIntentService，并没有补充了WAKE_LOCK权限，所以在8.0之前的系统上运行时，轻则像Flyme上的效果表现为无法正常自启，重则像原生系统上的效果表现为直接Crash。

4. 由于WAKE_LOCK不是敏感权限，所以直接在AndroidManifest中加入声明即可。
